// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHKg6WypBwcuvrhKFmatFOaaP2Ww-SYU',
    appId: '1:923416026215:web:746d5679345d81084e48c2',
    messagingSenderId: '923416026215',
    projectId: 'chat-app-b3623',
    authDomain: 'chat-app-b3623.firebaseapp.com',
    storageBucket: 'chat-app-b3623.appspot.com',
    measurementId: 'G-S0RTYSCQ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MjV4adAOjd3o4P5zsP_gpU-aRJSCy44',
    appId: '1:923416026215:android:f7ae5f90c8c95b844e48c2',
    messagingSenderId: '923416026215',
    projectId: 'chat-app-b3623',
    storageBucket: 'chat-app-b3623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOt5nCUcZqRLKCBarcMRZDpHxNOInrPSw',
    appId: '1:923416026215:ios:60398f9706bdd4e84e48c2',
    messagingSenderId: '923416026215',
    projectId: 'chat-app-b3623',
    storageBucket: 'chat-app-b3623.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOt5nCUcZqRLKCBarcMRZDpHxNOInrPSw',
    appId: '1:923416026215:ios:452a120c8afbe62c4e48c2',
    messagingSenderId: '923416026215',
    projectId: 'chat-app-b3623',
    storageBucket: 'chat-app-b3623.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
